AWSTemplateFormatVersion: "2010-09-09"
Description: |
  IAM Role for ECS Clusters

Resources:
  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref ECSRole

Outputs:
  ECSRole:
    Description: IAM Role for ECS Container Instances
    Value: !Ref ECSRole
    Export:
      Name: !Sub "${AWS::StackName}-ContainerInstanceRole"
